name       : python3-pycryptodome
version    : 3.4.3
release    : 2
source     :
    - https://pypi.python.org/packages/45/ef/4514a01be3d8f5383cd12fc5612ffd8a2508ac7e7ff6bde2da708e71c9a3/pycryptodome-3.4.3.tar.gz : 4b1697b5787afe8e7fd81b96ff4501376f52cb80fc9dd684f6989ea3b69853f4
license    :
    - BSD-2-Clause
    - MIT
component  : programming.python
summary    : PyCryptodome is a self-contained Python package of low-level cryptographic primitives
description: |
    PyCryptodome is a self-contained Python package of low-level cryptographic primitives
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
