name       : python3-pycryptodome
version    : 3.13.0
release    : 13
source     :
    - https://pypi.io/packages/source/p/pycryptodome/pycryptodome-3.13.0.tar.gz : 95bacf9ff7d1b90bba537d3f5f6c834efe6bfbb1a0195cb3573f29e6716ef08d
license    :
    - BSD-2-Clause
    - MIT
component  : programming.python
summary    : PyCryptodome is a self-contained Python package of low-level cryptographic primitives
description: |
    PyCryptodome is a self-contained Python package of low-level cryptographic primitives
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
