name       : python3-pycryptodome
version    : 3.10.1
release    : 10
source     :
    - https://pypi.io/packages/source/p/pycryptodome/pycryptodome-3.10.1.tar.gz : 3e2e3a06580c5f190df843cdb90ea28d61099cf4924334d5297a995de68e4673
license    :
    - BSD-2-Clause
    - MIT
component  : programming.python
summary    : PyCryptodome is a self-contained Python package of low-level cryptographic primitives
description: |
    PyCryptodome is a self-contained Python package of low-level cryptographic primitives
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
