name       : python3-pycryptodome
version    : 3.14.1
release    : 15
source     :
    - https://pypi.io/packages/source/p/pycryptodome/pycryptodome-3.14.1.tar.gz : e04e40a7f8c1669195536a37979dd87da2c32dbdc73d6fe35f0077b0c17c803b
homepage   : https://www.pycryptodome.org
license    :
    - BSD-2-Clause
    - MIT
component  : programming.python
summary    : Cryptographic library for Python
description: |
    PyCryptodome is a self-contained Python package of low-level cryptographic primitives.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
